### ISSUE TITLE
windows pricing...

### ISSUE THREAD

**Issue by abdulirfan3** [iconara/ec2pricing#12]
Hello -

Every time i change the drop down to "Windows" nothing happens.  The site does not populate prices for window server.  See attached.  Is this a known issue or ?

![image](https://user-images.githubusercontent.com/11415069/48282769-38ede000-e420-11e8-8b6b-a72f8b199a77.png)

**Comment by iconara** [comment]
It wasn't known, but looks like you're right. There's something bad with the data for the Windows instances. I noticed when I tried to update last that something had changed with the source data that made my import script break, it's possible that it had started earlier and I just didn't notice because it affected only Windows.

Thank you for reporting this. I don't have a lot of time to spend on this unfortunately, so I can't promise when it will be fixed.

**Comment by iconara** [comment]
I've rewritten the site to keep up to date automatically.
