### ISSUE TITLE
Is the pricing up to date?

### ISSUE THREAD

**Issue by benpoulson** [iconara/ec2pricing#13]
Text in the footer states

`The prices were last updated at 2018-12-14 17:16 using data published at 2018-12-13 20:49, `

Seeing as we're mid-2019, should there have been some updates?

**Comment by iconara** [comment]
Sorry, I haven't kept up. It's updated now.

I will probably have to figure out another way to distribute the pricing data, because the number of instances has increased a lot since I created the current version. Just in the last six months the pricing dump that the site is built from increased in size from 80 MB to over 600. The first time I deployed this version of the site my compacted pricing data was 2 MB gzipped, now it's almost 10.

**Comment by iconara** [comment]
I've rewritten the site to keep up to date automatically.
